### ISSUE TITLE
Specs are messed up

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/angular-native-dom-apis-lab#2]
My code is working in the browser, but the specs aren't passing. I tried changing both <span> and <h3> text to the changed text on click, but the specs still didn't pass. Submitted my code since it's passing in the browser.

**Comment by AnnJohn** [comment]
@aenser can you let us know what specifically in the specs weren't passing. Screenshots would be helpful. Thanks!

**Comment by aturkewi** [comment]
Mendel fixed issue with spec misaligning with lab in PR #4 

Closing
